apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsschool-back
  name: devopsschool-back
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devopsschool-back
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsschool-db
  name: devopsschool-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: devopsschool-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsschool-front
  name: devopsschool-front
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: devopsschool-front
  type: ClusterIP
